### ISSUE TITLE
Moving tasks to different projects

### ISSUE THREAD

**Issue by nielsk** [abrochard/emacs-todoist#12]
Is there a way to move a task to another project? I tried #projectname in the task name but that did not work. Moving the task to a project from the inbox and calling M-x todoist did not work either.

**Comment by abrochard** [comment]
I had the same question and the problem is that the current Todoist Rest API does not seem to support updating a task and changing its project id. https://developer.todoist.com/rest/v1/#update-a-task
I think the only way right now is to delete the task and recreate it under the project that you want.

**Comment by Lillenne** [comment]
@nielsk if you are still interested, [my implementation of org <--> Todoist sync](https://github.com/Lillenne/org-todoist) supports this feature by simply moving the headline or `org-refile`.
