### ISSUE TITLE
Internal Server Error becomes `json-readtable-error`

### ISSUE THREAD

**Issue by matthew-piziak** [abrochard/emacs-todoist#5]
Backtrace:
```
(json-readtable-error 73)
  signal(json-readtable-error (73))
  json-read()
  json-read-from-string("\nInternal Server Error\n")
  todoist--query("GET" "/projects")
  todoist--get-projects()
  todoist()
```

**Comment by abrochard** [comment]
Thanks for reporting this. I will strengthen the error handling in `todoist--query` to display proper error messages

**Comment by matthew-piziak** [comment]
Thank you!

**Comment by rbirkelbach** [comment]
I also get this error. I use macOS Mojave with spacemacs. I set the api key via an environment variable.

**Comment by brandelune** [comment]
same error here...

**Comment by abrochard** [comment]
I just merged https://github.com/abrochard/emacs-todoist/pull/11 which will solve part of the issue.
The real problem here is that if the todoist API returns anything that isn't JSON, the current code completely gives up. The fix will reduce the occurrences but the longer term solution is to handle the API returning malformed results and displaying the error.

**Comment by abrochard** [comment]
I just added another commit to handle when the server returns something else than a 2XX status code and throw an exception. I will close this issue for now. Feel free to re-open if you see anything abnormal.
